config/routes.rb
Blocmarks::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  #resources :users, only: [:show, :update]
  resources :topics do
    resources :bookmarks, except: [:index] do
    resources :likes, only: [:create, :destroy]
  end
end

   #resources :bookmarks do 
   
  #end
  resources :likes, :users
  
  #devise_scope :user do
    #get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  #end

  get 'welcome/about'

  root to: 'site#index'

  post :incoming, to: 'incoming#create'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  #include SimpleHashtag::Hashtaggable
  belongs_to :user
  has_many :likes, dependent: :destroy
  belongs_to :topic
  default_scope { order('created_at DESC') } 

  validates :user_id, presence: true
  validates :title, length: {minimum: 2}, presence: true
  validates :topic, presence: true
  #validates :url, format: {with: Regexp.new(URI::regexp(%w(http https)))}, presence: true
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @bookmarks = current_user.bookmarks.all
  end
  
  def show
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = current_user.bookmarks.new
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    @topic = Topic.find(params[:topic_id])
    #@bookmark = current_user.bookmarks.new(bookmark_params)
    @bookmark = current_user.bookmarks.build(params.require(:bookmark).permit(:title))
    @bookmark.topic = @topic

    if @bookmark.save
      flash[:notice] = "Bookmark was saved."
      redirect_to [@topic, @bookmark]
    else
      flash[:error] = "There was an error saving the bookmark. Please try again."
      render action: 'new'
    end
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    #if @bookmark.update(bookmark_params)
    if @bookmark.update_attributes(params.require(:bookmark).permit(:title))
      flash[:notice] = "Bookmark was updated."
      redirect_to [@topic, @bookmark]
    else
      flash[:error] = "There was an error saving the bookmark. Please try again."
      render :edit
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.'
  end

  def like
    bookmark = resource.like current_user
    Event.bookmark_liked!(bookmark)
    redirect_to discussion_url(resource.discussion)
  end

  def unlike
    resource.unlike current_user
    redirect_to discussion_url(resource.discussion)
  end

  private
    def set_bookmark
      unless @bookmark = current_user.bookmarks.where(id: params[:id]).first
      flash[:alert] = 'Bookmark not found.'
      redirect_to root_url
    end
  end

    def bookmark_params
      params.require(:bookmark).permit(:title, :url)
    end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@topic, @bookmark] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing blocmark</h1>

<%= render 'form' %>

<%= link_to 'Back', topic_bookmark_path %>

app/views/bookmarks/index.html.erb
<% if current_user %>
<h1>My Blocmarks Bookmarks</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Time created</th>
    
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.title %></td>
        <td><%= bookmark.url %></td>

        <td><%= link_to 'Show', bookmark %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
        <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% end %>
<%= link_to 'New Bookmark', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= render partial: 'form' %>

<%= link_to 'Back', topic_bookmarks_path %>

app/views/bookmarks/show.html.erb
<h1><%= @bookmark.title %></h1>

  <%= @bookmark.url %>
  <%= render partial: 'likes/like', locals: { bookmark: @bookmark } %>
  <br>

  <%= link_to 'Edit', edit_topic_bookmark_path(@topic, @bookmark), class: 'btn btn-info' %> |
  <%= link_to 'Back', topic_bookmark_path %>