config/routes.rb
Blocmarks::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  #resources :users, only: [:show, :update]
  resources :topics do
    resources :bookmarks, except: [:index] do
    resources :likes, only: [:create, :destroy]
  end
end

   #resources :bookmarks do 
   
  #end
  resources :likes, :users
  
  #devise_scope :user do
    #get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  #end

  get 'welcome/about'

  root to: 'site#index'

  post :incoming, to: 'incoming#create'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :bookmarks#, dependent: :destroy
  has_many :likes
  default_scope { order('created_at DESC') } 

  validates :name, length: {minimum: 5}, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all
    @like = Like.new
   # @topics = @topics.sort {|a, b| b.bookmarks <=> a.bookmarks }
  end

  def new
    @topic = Topic.new
  end

  def show
    #@topic = Topic.find_by_name(params[:id])
    @topic = Topic.find(params[:id])
    @bookmarks = @topic.bookmarks
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def create
    @topic = Topic.new(params.require(:topic).permit(:name, :public))
    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash[:error] = "Error creating topic. Please try again."
      render :new
    end
      #@topic = Topic.find_by_name(params[:name])
    #unless @topic
      #@topic = Topic.new(name: params[:name])
      #@topic.save
    #end
  #end
   end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update(topic_params)
      redirect_to @topic, notice: 'Topic successfully updated.'
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @topic = Topic.find(params[:id])
    name = @topic.name

    if @topic.destroy
      flash[:notice] = "\"#{name}\" was deleted successfully."
      redirect_to topics_path
    else
      flash[:error] = "There was an error deleting the topic."
      render :show
    end
  end

  

  private
    def topic_params
      params.require(:topic).permit(:name)
    end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="col-md-8">
  <%= form_for @topic do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
    </div>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  </div>
</div>
  <% end %>

app/views/topics/edit.html.erb
<%= render partial: 'form' %>

app/views/topics/index.html.erb
<h1>Topics</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="5">Options</th>
    </tr>
  </thead>
  <tbody>
    <% @topics.each do |topic| %>
     <tr>
        <td><%= link_to topic.name, topic %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
     </tr>
    <% end %>
  </tbody>
</table>

<div class="col-md-4">
  <% if true %>
    <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
  <% end %>
</div>


      

       

app/views/topics/new.html.erb
<h1>New Topic</h1>
  <div class="row">
    <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
        <%= f.button :submit %>
    <% end %>
      </div>  
    </div>
  </div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>
    <% @bookmarks.each do |bookmark| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to bookmark.title, [@topic, @bookmark] %> 
          </h4>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
      <%= link_to "New Bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-success' %>
      <%= link_to 'Back', topic_path %>
  </div>
</div>