config/routes.rb
Blocmarks::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  #resources :users, only: [:show, :update]
  resources :topics do
    resources :bookmarks, except: [:index] do
    resources :likes, only: [:create, :destroy]
  end
end

   #resources :bookmarks do 
   
  #end
  resources :likes, :users
  
  #devise_scope :user do
    #get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  #end

  get 'welcome/about'

  root to: 'site#index'

  post :incoming, to: 'incoming#create'
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
  belongs_to :topic
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def create
     
    @bookmark = Bookmark.find(params[:bookmark_id])
   # @topic = Topic.find(params[:topic_id])
     like = current_user.likes.build(bookmark: @bookmark)
     #authorize like
     if like.save
      redirect_to :back, notice: "Bookmark liked!"
    else
      flash[:error] = "There was an error liking this blocmark, please try again"
      redirect_to :back
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    #@topic = Topic.find(params[:topic_id])
    like = current_user.likes.find_by(bookmark: @bookmark)
    #authorize like
    if like.destroy
      redirect_to :back, notice: "Bookmark unliked!"
    else
      flash[:error] = "There was an error unliking this blocmark, please try again"
      redirect_to :back
    end
  end
end

              

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/ _like.html.erb
<% if bookmark.user == current_user %>
  <%= link_to bookmark_path(bookmark), class: 'btn btn-danger center-block space-bottom', method: :delete  do %>
    <i class="glyphicon glyphicon-remove"> </i>&nbsp; Delete Blocmark
  <% end %>
<% elsif bookmark.liking_users.include?(current_user) %>
  <%= link_to bookmark_like_path(bookmark), class: 'btn btn-danger center-block space-bottom', method: :delete do %>
    <i class="glyphicon glyphicon-star"> </i>&nbsp; Unlike Blocmark
  <% end %>
<% else %>
  <%= link_to bookmark_like_path(bookmark), class: 'btn btn-primary center-block space-bottom', method: :post do %>
    <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Like Blocmark
  <% end %>
<% end %>

app/views/likes/_like.html.erb
<div class="like">
  <% if like = current_user.liked(bookmark) %>
    <%= link_to [@topic, bookmark, like], class: 'btn btn-danger', method: :delete do %>
      <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
    <% end %>
  <% else %>
    <%= link_to [@topic, bookmark, Like.new], class: 'btn btn-primary', method: :post do %>
      <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
    <% end %>
  <% end %>
</div>