config/routes.rb
Blocmarks::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  #resources :users, only: [:show, :update]
  resources :topics do
    resources :bookmarks, except: [:index] do
    resources :likes, only: [:create, :destroy]
  end
end

   #resources :bookmarks do 
   
  #end
  resources :likes, :users
  
  #devise_scope :user do
    #get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  #end

  get 'welcome/about'

  root to: 'site#index'

  post :incoming, to: 'incoming#create'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Blocmarks" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
   <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : 'your-app-id',
          xfbml      : true,
          version    : 'v2.1'
        });
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>

    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#blocmarks-navbar-collapse">
      <h3>
        <%= link_to 'Home |', root_path, class: 'navbar-brand' %> 
        <%= link_to 'Topics |', topics_path, class: 'navbar-brand' %>
        <%= link_to 'About |', welcome_about_path, class: 'navbar-brand' %>  
      </h3>
    </div>

  <div class="container">


       <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
             <div><%= image_tag current_user.image %></div>
           <% else %>
             
             
           <% end %>
         </div>
        

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>